### ISSUE TITLE
Doesn't capitalize an uppercase word

### ISSUE THREAD

**Issue by seandelaney** [zeke/ap-style-title-case#4]
I've used this package in a project and noticed uppercase words are ignored, which is not ideal.

This is a bug or is this library not meant to capitalize uppercase words?

<img width="636" alt="Screenshot 2019-04-18 at 11 45 26" src="https://user-images.githubusercontent.com/580403/56356190-08308480-61d0-11e9-9b9c-c647a6dcbb7b.png">

**Comment by zeke** [comment]
Hey there. Nice use of RunKit to display the issue. 👍 

I think the current behavior makes the most sense, because If a string contains an acronym, we wouldn't want to mess it up: `IBM builds new CAPTHCA tool` -> `Ibm Builds New Captcha Tool`. Open to ideas on how to support your use case though.. maybe introducing an option?

**Comment by seandelaney** [comment]
Good point about acronyms!

An option would be handy to enforce rules regardless of the current text case.

**Comment by zeke** [comment]
@seandelaney feel free to open an exploratory PR to add such an option.
